//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lista3
{
    using Lista3.Properties;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Drawing;
    using System.IO;
    using System.Windows.Media.Imaging;

    public partial class Student
    {
        public string id_stud { get; set; }
        public string SURNAME { get; set; }
        public string NAME { get; set; }
        public System.DateTime BIRTHDATE { get; set; }
        public int AGE { get; set; }
        public string ADRESS_CITY { get; set; }
        public string ADRESS_STREET { get; set; }
        public string PESEL { get; set; }
        public string NR_ALBUM { get; set; }

        public byte[] STUDENT_IMAGE
        {

            get
            {




                if (ByteImage==null)
                {
                   return ImageToByte((Bitmap)Resources.no_image);
                }
                else
                {
                    return ByteImage;
                }
                
              
            }

            set
            {
                
            }


        }


        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public BitmapImage ImgSource 
        {

            get 
            {

                return BitmapToImageSource((Bitmap)((new ImageConverter()).ConvertFrom(STUDENT_IMAGE)));

            }
        }

        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public byte[] ByteImage;



        public void AddImage(Image img)
        {
            ImageConverter converter = new ImageConverter();
            ByteImage = (byte[])converter.ConvertTo(img, typeof(byte[]));
        }


        private byte[] ImageToByte(Image img)
        {
            ImageConverter converter = new ImageConverter();
            return (byte[])converter.ConvertTo(img, typeof(byte[]));
        }


        public BitmapImage GetImage()
        {
            return BitmapToImageSource((Bitmap)((new ImageConverter()).ConvertFrom(STUDENT_IMAGE)));
        }

        private BitmapImage BitmapToImageSource(Bitmap bitmap)
        {
            using (MemoryStream memory = new MemoryStream())
            {
                bitmap.Save(memory, System.Drawing.Imaging.ImageFormat.Bmp);
                memory.Position = 0;
                BitmapImage bitmapimage = new BitmapImage();
                bitmapimage.BeginInit();
                bitmapimage.StreamSource = memory;
                bitmapimage.CacheOption = BitmapCacheOption.OnLoad;
                bitmapimage.EndInit();

                return bitmapimage;
            }
        }

        public void SetId()
        {
            id_stud = Guid.NewGuid().ToString();
        }

        public static void Copy(Student copyfrom, Student copyto)
        {
            copyto.ADRESS_STREET = copyfrom.ADRESS_STREET;
            copyto.NAME = copyfrom.NAME;
            copyto.SURNAME = copyfrom.SURNAME;
            copyto.PESEL = copyfrom.PESEL;
            copyto.id_stud = copyfrom.id_stud;
            copyto.ADRESS_CITY = copyfrom.ADRESS_CITY;
            copyto.NR_ALBUM = copyfrom.NR_ALBUM;
            copyto.AGE = copyfrom.AGE;
            copyto.BIRTHDATE = copyfrom.BIRTHDATE;
            copyto.STUDENT_IMAGE = copyfrom.STUDENT_IMAGE;



        }


    }
}
